// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwQ7eudDkH7wr-o_SOHr6EY447m9tY4uY',
    appId: '1:213538569628:web:2e560edfa7f54d4bafdc59',
    messagingSenderId: '213538569628',
    projectId: 'provider-student-management',
    authDomain: 'provider-student-management.firebaseapp.com',
    storageBucket: 'provider-student-management.appspot.com',
    measurementId: 'G-709C18GEJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtW4GvHxNhFw35qhp63_mpYn4xLFULM_8',
    appId: '1:213538569628:android:525737fd912a0db3afdc59',
    messagingSenderId: '213538569628',
    projectId: 'provider-student-management',
    storageBucket: 'provider-student-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0mbsJdiQo_G2XakxadIB8g-CrpGRvGfY',
    appId: '1:213538569628:ios:bfff7753a4f1095aafdc59',
    messagingSenderId: '213538569628',
    projectId: 'provider-student-management',
    storageBucket: 'provider-student-management.appspot.com',
    iosBundleId: 'com.example.providerStudentManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0mbsJdiQo_G2XakxadIB8g-CrpGRvGfY',
    appId: '1:213538569628:ios:932421c5d559297cafdc59',
    messagingSenderId: '213538569628',
    projectId: 'provider-student-management',
    storageBucket: 'provider-student-management.appspot.com',
    iosBundleId: 'com.example.providerStudentManagementApp.RunnerTests',
  );
}
